<?xml version="1.8" encoding="UTF-8"?>
<!DOCTYPE employee[
<!ELEMENT name (#PCDATA)>
<!ELEMENT salary (#PCDATA)>
<!ELEMENT Dob (#PCDATA)>
]>

<employee>
<name>Mrinal</name>
<salary>100000</salary>
<Dob>27 JUlY 2004</Dob>
<name>Sanika</name>
<salary>50000</salary>
<Dob>12 JUNE 2004</Dob>
<name>Swapnali</name>
<salary>50000</salary>
<Dob>5 OCTOBER 2004</Dob>
</employee>

